export interface IApplication {
  familyNameCN?: string
  givenNameCN?: string
  familyName?: string
  givenName?: string
  birthday?: Date
  birth_place?: string
  gender?: string
  chinese_id?: string
  marital_status?: string
  home_address?: string
  tel?: string
  email?: string
  last_enter_date?: Date
  last_duration?: Date
  employer_name?: string
  employer_tel?: string
  employer_address?: string
  occupation?: string
  passport_number?: string
  passport_issued_place?: string
  passport_issued_authority?: string
  passport_issued_date?: Date
  passport_expiry_date?: Date
  guarantor_name_en?: string
  guarantor_name?: string
  guarantor_tel?: string
  guarantor_address_en?: string
  guarantor_address?: string
  guarantor_birthday?: string
  guarantor_relationship?: string
  guarantor_occupation?: string
  guarantor_nationality?: string
  guarantor_visa?: string
}